### PR TITLE
Bank account model test

### PR DESCRIPTION
**Pull request by igorsergiichuk**
## Overview

| Q                 | A
| ----------------- | ---
| Bugfix?           | no
| New feature?      | yes
| Breaking Changes? |no
| Fixed issues      | #

## The problem

BankAccountModelTest was missing

## How I resolved it

Added it!

## How to verify it

Test it!

Notify the following people: @darrynten

### CODE REVIEW

**Review by fergusdixon — COMMENTED** [review]
Looks good to me, nice job

**Review by darrynten — DISMISSED** [review]
Looking good bro! Just wondering why that's failing on Travis

**Comment by darrynten** [comment]
Hi @igorsergiichuk this one has conflicts and a failing Travis build. You can click the details link next to the fail notification to see the details of the error.

**Review by darrynten — APPROVED** [review]
Looking good!

**Pull request merged**
